### ISSUE TITLE
receipt

### ISSUE THREAD

**Issue by NajwanHensem** [NajwanHensem/SE-Lab-Team#16]

**Comment by M429D** [comment]
![Image](https://user-images.githubusercontent.com/92875016/199667029-37ec511b-cad7-429b-b6ab-00b04ffbad0c.png)

Review please.

**Comment by NajwanHensem** [comment]
NA SHOULD BE NO

**Comment by M429D** [comment]
![Image](https://user-images.githubusercontent.com/92875016/199667242-0b51ef83-af1c-4819-9b9d-042ef69d5a7c.png)

Updated sir

**Comment by NajwanHensem** [comment]
ORITE NICE
