### ISSUE TITLE
Inactive alert Prompt

### ISSUE THREAD

**Issue by M429D** [NajwanHensem/SE-Lab-Team#20]

**Comment by M429D** [comment]
![Image](https://user-images.githubusercontent.com/92875016/199677187-cc76aa43-fa42-454f-bb1a-f9f591c396e9.png)

This ok?

**Comment by NajwanHensem** [comment]
usually its more than 5 seconds

**Comment by NajwanHensem** [comment]
since according to thew contoh is 5 secs then its ok
