### ISSUE TITLE
PIN

### ISSUE THREAD

**Issue by NajwanHensem** [NajwanHensem/SE-Lab-Team#4]

**Comment by NajwanHensem** [comment]
![image](https://user-images.githubusercontent.com/117338783/199671673-c2541dcd-f8c9-459d-832c-42f13360ffb1.png)
THIS IS OK?

**Comment by M429D** [comment]
please put pin picture

**Comment by NajwanHensem** [comment]
is this ok?
![Uploading Capture.JPG…]()

**Comment by NajwanHensem** [comment]
HELLO

**Comment by NajwanHensem** [comment]
CMNI JE OK

**Comment by NajwanHensem** [comment]
TPI BILA NK GAMBAR DIA X NK UPLOAD

**Comment by M429D** [comment]
haha

**Comment by NajwanHensem** [comment]
![Uploading New PIN GUI.JPG…]()
DIA JDI CMNI

**Comment by M429D** [comment]
![Image](https://user-images.githubusercontent.com/92875016/199780293-b889ce9a-d893-4305-b5d2-fdadae7edd4d.png)

This ok boss

**Comment by NajwanHensem** [comment]
yup this is ok
