### ISSUE TITLE
Processing interface

### ISSUE THREAD

**Issue by NajwanHensem** [NajwanHensem/SE-Lab-Team#6]

**Comment by NajwanHensem** [comment]
IS THIS  OK

**Comment by NajwanHensem** [comment]
![Uploading Capture.JPG…]()
IS THIS OK

**Comment by NajwanHensem** [comment]
![Capture](https://user-images.githubusercontent.com/117338783/199671426-d6e7ef8d-e948-4b63-915d-6e10e95ae875.JPG)
THIS ONE?

**Comment by M429D** [comment]
Approved.
