### ISSUE TITLE
Select language interface

### ISSUE THREAD

**Issue by NajwanHensem** [NajwanHensem/SE-Lab-Team#7]

**Comment by NajwanHensem** [comment]
![image](https://user-images.githubusercontent.com/117338783/199669860-f83742e5-12ef-4162-bf50-2e6ea9e4abb2.png)
 IS THIS OK?

**Comment by M429D** [comment]
Please include Chinese option.

**Comment by NajwanHensem** [comment]
![image](https://user-images.githubusercontent.com/117338783/199670177-5ba4fbc3-5ff4-4025-aa80-b3daab1f4726.png)
THIS IS OK?

**Comment by M429D** [comment]
Nice...accepted.
